### ISSUE TITLE
[Android Bootcamp] Project 5: Twitter with Fragments - Ready for Review

### ISSUE THREAD

**Issue by lwhsu** [lwhsu/SimpleTwitterClient#2]
My app is complete, please review.

Thanks!

/cc @nidhi1608 @thecodepath

Li-Wen Hsu lwhsu@yahoo-inc.com

**Comment by nidhi1608** [comment]
:+1: Project looks good. I have provided a detailed [Feedback Guide here](https://gist.github.com/nesquena/d88cf3606a308359323f) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you might be able to improve your submission.

Let us know if you have any other thoughts or questions about this assignment. Hopefully you can see this coming together as a "fully fledged" twitter client with some more work and polish. This app contains all of the components now (fragments, models, networking, client, tab navigation, image loading, et al) of 90% of dynamic data-driven API client. Obviously there are lots of details and patterns to learn, but by this point you have been introduced to all the major frameworks and concepts. Hopefully you would feel fairly confident getting started making Android apps for pinterest, yardsale or flickr using the same patterns.
